#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-nethvoice-update event
#
#

my $event = 'nethserver-janus-update';

event_actions($event, qw(
    initialize-default-databases 00
));

event_templates($event, qw(
    /opt/janus/etc/janus/janus.cfg
    /opt/janus/etc/janus/janus.plugin.sip.cfg
    /opt/janus/etc/janus/janus.transport.http.cfg
    /opt/janus/etc/janus/janus.transport.pfunix.cfg
    /opt/janus/etc/janus/janus.transport.websockets.cfg
    /opt/janus/share/janus/certs/cert.pem
    /opt/janus/share/janus/certs/cert.key
));

templates2events("/opt/janus/share/janus/certs/cert.pem","certificate-update");
templates2events("/opt/janus/share/janus/certs/cert.key","certificate-update");

event_services($event ,qw(
        janus-gateway restart
        httpd reload
));

